name: AICKernel
channels:
  - conda-forge
dependencies:
  - python=3.7
  - matplotlib
  - scipy
  - plotly
  - dill
  - peakutils
  - lmfit
  - nptdms
  - jupyter
  - nibabel
  - papermill
  - openpyxl
  - pip:
    - lvm_read
