name: calciumAIC
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - scipy
  - pandas
  - plotly
  - nb_conda
  - nb_conda_kernels
  - ipykernel
  - ipywidgets
  - dill
  - peakutils
  - lmfit
  - nptdms
  - jupyter
  - pip:
    - lvm_read